server:
  port: 8083  # Port for the order service

spring:
  application:
    name: order  # The name registered in Eureka

  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/orderMicroServ?createDatabaseIfNotExist=true
    password:  # Provide the password if needed
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  cloud:
    discovery:
      enabled: true  # Enable Eureka client
    # Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
  instance:
    hostname: localhost  # Ensure this is correct if Eureka is running locally

# Optional: logging to troubleshoot further
logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG  # Enable DEBUG logging for Eureka
    org.springframework.web.client.RestTemplate: DEBUG  # Enable DEBUG logging for RestTemplate (helps in tracing the requests)
